name: Test workflow

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2        
      # Setup python 3.8
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8          
      # Install python script dependencies
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "scripts/requirements.txt"      
      # List files
      - name: List content
        run: ls
      # Runs test script      
      - name: Test script
        working-directory: ./scripts
        env:
          FDP_URL: ${{ vars.FDP_URL }}
          FDP_PERSISTENT_URL: ${{ vars.FDP_PERSISTENT_URL }}
          FDP_USERNAME: ${{ secrets.FDP_USERNAME }}
          FDP_PASSWORD: ${{ secrets.FDP_PASSWORD }}
          BASE_PATH: ".."
          CONFIG_FILE: "../config.yml"
        run: python main.py
